# Copyright Â© 2025 Cassidy Spring (Bee). Folklore Project.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 10
    directory: /
    schedule:
      interval: weekly
    assignees:
      - beeauvin

  - package-ecosystem: swift
    open-pull-requests-limit: 10
    directory: /
    schedule:
      interval: weekly
    assignees:
      - beeauvin
